/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:615a774c-682f-4bdf-9e81-ea3e9d519761",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CPkhDEEIg",
    "aws_user_pools_web_client_id": "7e5essuokd7p7l29ruf6jdoht9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://qonybhui7zbujfgzpolrfcd2ta.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
